name: liam_test

# "-" in compose means a list!

services:
  foo:
    image: busybox
    command: echo "Im learning Docker compose and this is my project ${COMPOSE_PROJECT_NAME}"
  web:
    build: . # tells compose to build our application from our source "." here!
    ports:
      - "${APP_PORT}:5000"

    environment:
      - REDIS_HOST=${REDIS_HOST} # Maps the host (my pc) port to 5000
      - REDIS_PORT=${REDIS_PORT} # redis port is 6367 or smth
    
    depends_on: # this says, the web block will only run if redis is running!
      redis:
        condition: service_healthy
    
  redis:
    image: redis:alpine # runs a apline "smaller" version of redis!
    healthcheck: # runs a health check to validate the redis status!
      test: ["CMD", "redis-cli", "ping"] # pings redis
      interval: 5s # every 5 seconds
      timeout: 3s # gives 3 seconds to respond!
      retries: 5 # how many consecutive Fails are allowed!
      start_period: 10s # gives redis 10 seconds to prepare and initialize itself

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml # Bind Mount (Config)
     - prometheus-data:/prometheus # Named Volume (Database history)
    depends_on:
      - web
  
  grafana:
    image: grafana/grafana-oss:latest # official image!
    ports:
      - "3000:3000" # default ports for GRAFANA UI!
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pucpr_admin # Set your own password!
    volumes:
     - grafana-storage:/var/lib/grafana # data persistency, creating a volume makes so data isnt stored in the container but in the host's pc!
    depends_on:
      - prometheus

    ## My ollama Service!! <3
  ollama:
    volumes:
      - ollama-data:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - "11434:11434" # Default Ollama Port

# This section tells Docker to manage these "Storage Units"
volumes:
  ollama-data:
  prometheus-data:
  grafana-storage:

    